updates to install script

diff --git a/install-dsptoolkit b/install-dsptoolkit
--- a/install-dsptoolkit
+++ b/install-dsptoolkit
@@ -23,47 +23,70 @@ sudo apt install python3-pip libasound2-dev libxslt1-dev libxml2-dev zlib1g-dev 
 # done
 
 
-DSPTOOLKIT_ROOT="$TYEFI_ROOT/lib/hifiberry/dsptoolkit"
-
-echo "TYEFI_ROOT set to $TYEFI_ROOT"
-echo "DSPTOOLKIT_ROOT set to $DSPTOOLKIT_ROOT"
-
-
-
-if [[ ! -d "$TYEFI_ROOT/.venv" ]]; then
-    echo "installing python virtual environment"
-    sudo python3 -m venv .venv
-else
-    echo "python virtual environment already exists"
+if [[ -z "$DSPTOOLKIT_ROOT" ]]; then
+    warn "DSPTOOLKIT_ROOT is not set"
+    echo "please set DSPTOOLKIT_ROOT to the root of the dsptoolkit project"
+    DSPTOOLKIT_ROOT="$TYEFI_ROOT/lib/hifiberry-dsp"
+    exit 1
 fi
 
-PY_BIN="$TYEFI_ROOT/.venv/bin"
 
-echo "activating python virtual environment"
-source "$PY_BIN/activate"
+verbose "TYEFI_ROOT set to $TYEFI_ROOT"
+verbose "DSPTOOLKIT_ROOT set to $DSPTOOLKIT_ROOT"
+
+
+# install python venv separate from tyefi since it has conflicting dependencies (RPi.GPIO)
+PY_ENV="$DSPTOOLKIT_ROOT/.venv"
+PY_BIN="$PY_ENV/bin"
+
+
+if [[ ! -d "$PY_ENV" ]]; then
+    info "installing python virtual environment at $PY_ENV"
+    sudo python3 -m venv --system-site-packages "$PY_ENV"
+else
+    verbose "python virtual environment already exists at $PY_ENV"
+fi
+
+if [[ -z "$VIRTUAL_ENV" ]]; then
+    echo "activating python virtual environment"
+    source "$PY_BIN/activate"
+else
+    echo "python virtual environment already activated"
+fi
+
+
+if [[ -z "$PY_BIN" || ! -d "$PY_BIN" || -z "$VIRTUAL_ENV" ]]; then
+    fatal "python virtual environment not found or activated correctly. make sure this script is run using "$TYEFI_ROOT/lib/install_libs.sh""
+    # info "installing python virtual environment at $PY_ENV"
+    # sudo python3 -m venv --system-site-packages "$PY_ENV"
+fi
+
+if [[ ! -d /var/lib/hifiberry ]]; then
+    info "creating /var/lib/hifiberry"
+    sudo mkdir -p /var/lib/hifiberry
+fi
+
 
 echo "installing dsptoolkit"
-sudo "$TYEFI_ROOT/.venv/bin/pip3" install -e "$DSPTOOLKIT_ROOT"
+sudo "$PY_BIN/pip3" install -e "$DSPTOOLKIT_ROOT"
 
 
-sudo mkdir -p /var/lib/hifiberry
-
-BIN="$TYEFI_ROOT/lib/hifiberry/dsptoolkit/bin"
+BIN="$DSPTOOLKIT_ROOT/bin"
 ANSWER="y"
 
-if [[ -f /lib/systemd/system/sigmatcp.service ]]; then
-    echo "sigmatcp service already exists, would you like to remove it? (y/n)"
-    read -r ANSWER
+# if [[ -f /lib/systemd/system/sigmatcp.service ]]; then
+#     echo "sigmatcp service already exists, would you like to remove it? (y/n)"
+#     read -r ANSWER
 
-    if [[ "$ANSWER" == "y" ]]; then
-        echo "removing existing sigmatcp service"
-        for i in sigmatcp; do
-            sudo systemctl stop $i
-            sudo systemctl disable $i
-        done
-        sudo rm /lib/systemd/system/sigmatcp.service
-    fi
-fi
+#     if [[ "$ANSWER" == "y" ]]; then
+#         echo "removing existing sigmatcp service"
+#         for i in sigmatcp; do
+#             sudo systemctl stop $i
+#             sudo systemctl disable $i
+#         done
+#         sudo rm /lib/systemd/system/sigmatcp.service
+#     fi
+# fi
 
 if [[ "$ANSWER" == "y" ]]; then
     echo "installing sigmatcp service at $BIN/sigmatcpserver"
@@ -95,10 +118,10 @@ fi
 
 
 
-CFG_PATH=/boot/config.txt
+CFG_PATH=/boot/firmware/config.txt
 
 if [[ ! -f "$CFG_PATH" ]]; then
-    CFG_PATH=/boot/firmware/config.txt
+    CFG_PATH=/boot/config.txt
 
     if [[ ! -f "$CFG_PATH" ]]; then
         echo "config.txt not found at /boot/config.txt or /boot/firmware/config.txt"
